ShuffleArray.md
DevTMK/snips pull request #17
Opened 2022-10-11 15:10 UTC by void-57

2022-10-11 15:19 UTC, DevTMK requested changes
@void-57 You are not supposed to remove template.md file
and move the snip file to [`src`](https://github.com/DevTMK/snips/blob/main/src) folder

2022-10-11 15:21 UTC, void-57 commented
oh sorry i will do again

2022-10-11 15:23 UTC, DevTMK requested changes

2022-10-11 15:23 UTC, DevTMK commented on ShuffleArray.md
> +
Add short description here

2022-10-11 15:23 UTC, DevTMK commented on ShuffleArray.md
> +  #include <bits/stdc++.h>
See if you can do it without any external dependancy

2022-10-11 15:23 UTC, DevTMK commented on ShuffleArray.md
> +int main()
Just keep the shuffle function

2022-10-11 15:26 UTC, void-57 commented on ShuffleArray.md
> +int main()
okk

2022-10-16 07:08 UTC, DevTMK commented
It's been a long, there are no changes. Closing this PR for now

2022-10-16 07:08 UTC, closed without merging