added snip for random number genetor
DevTMK/snips pull request #36
Opened 2022-10-18 11:41 UTC by savi001

added snip for randon number generator within a given range, please specify if any change is required

2022-10-18 18:04 UTC, DevTMK commented
Hey @savi001, you are supposed to create a new snip in the src folder.
Take a look at [contributing guidelines](https://github.com/DevTMK/snips/blob/9661c2f0362c46d8383ef5a5a18f0a557052dfde/CONTRIBUTING.md).

2022-10-18 18:05 UTC, DevTMK requested changes

2022-10-18 18:05 UTC, DevTMK commented on RandomNumberGenerator.md
> +  <script>
Just keep the function, remove other code

2022-10-19 02:32 UTC, savi001 commented
what should i have to write in "Add final result here" section

2022-10-19 16:44 UTC, DevTMK commented on RandomNumberGenerator.md
> +console.log(randomNumber( 1, 100 )); // 68
It should be -
randomNumber(1, 100); // 68

2022-10-20 07:50 UTC, savi001 commented
see if any futher change is required

2022-10-20 17:04 UTC, DevTMK approved these changes
Thanks @savi001, Merging

2022-10-20 17:08 UTC, merged